name: lawly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  flutter_native_splash: 2.4.6
  provider: 6.1.4
  dio: ^5.8.0+1
  auto_route: ^10.0.1
  elementary: ^3.2.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  shared_preferences: 2.5.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  retrofit: ^4.4.2
  device_info_plus: ^11.4.0
  union_state: ^0.0.3
  flutter_markdown: ^0.7.7
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  retrofit_generator: ^9.1.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/welcome/
    - assets/icons/
    - assets/icons/common/
    - assets/icons/bottom_nav_screen_icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/images/logo500.png
  color: "#F2EDE7"
  android_12:
    # Показываем белый экран на системном сплеше android 12+ 
    image: assets/images/logo_2.png
    color: "#F2EDE7"